<?php

namespace Database\Seeders;

use App\Models\InventoryItem;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // Aftercare Products
            [
                'name' => 'Acne Cream',
                'sku' => 'AC-001',
                'category' => 'Aftercare Products',
                'description' => 'Acne treatment cream for post-treatment care',
                'cost_price' => 250.00,
                'selling_price' => 250.00,
                'current_stock' => 50,
                'minimum_stock' => 10,
                'unit' => 'piece',
                'supplier' => 'K-Derma Supplies',
                'expiry_date' => now()->addMonths(24),
                'is_active' => true,
            ],
            [
                'name' => 'Toner',
                'sku' => 'TN-001',
                'category' => 'Aftercare Products',
                'description' => 'Facial toner for daily skincare routine',
                'cost_price' => 300.00,
                'selling_price' => 300.00,
                'current_stock' => 40,
                'minimum_stock' => 10,
                'unit' => 'bottle',
                'supplier' => 'K-Derma Supplies',
                'expiry_date' => now()->addMonths(18),
                'is_active' => true,
            ],
            [
                'name' => 'Sunscreen',
                'sku' => 'SS-001',
                'category' => 'Aftercare Products',
                'description' => 'Sun protection cream for daily use',
                'cost_price' => 300.00,
                'selling_price' => 300.00,
                'current_stock' => 45,
                'minimum_stock' => 10,
                'unit' => 'tube',
                'supplier' => 'K-Derma Supplies',
                'expiry_date' => now()->addMonths(24),
                'is_active' => true,
            ],
            [
                'name' => 'Foaming Wash',
                'sku' => 'FW-001',
                'category' => 'Aftercare Products',
                'description' => 'Gentle foaming facial cleanser',
                'cost_price' => 350.00,
                'selling_price' => 350.00,
                'current_stock' => 35,
                'minimum_stock' => 10,
                'unit' => 'bottle',
                'supplier' => 'K-Derma Supplies',
                'expiry_date' => now()->addMonths(18),
                'is_active' => true,
            ],
            [
                'name' => 'Soap',
                'sku' => 'SP-001',
                'category' => 'Aftercare Products',
                'description' => 'Gentle cleansing soap for sensitive skin',
                'cost_price' => 150.00,
                'selling_price' => 150.00,
                'current_stock' => 60,
                'minimum_stock' => 15,
                'unit' => 'bar',
                'supplier' => 'K-Derma Supplies',
                'expiry_date' => now()->addMonths(12),
                'is_active' => true,
            ],
            [
                'name' => 'Day & Night Cream',
                'sku' => 'DNC-001',
                'category' => 'Aftercare Products',
                'description' => 'Moisturizing cream for day and night use',
                'cost_price' => 300.00,
                'selling_price' => 300.00,
                'current_stock' => 30,
                'minimum_stock' => 8,
                'unit' => 'jar',
                'supplier' => 'K-Derma Supplies',
                'expiry_date' => now()->addMonths(18),
                'is_active' => true,
            ],
            [
                'name' => 'Package',
                'sku' => 'PKG-001',
                'category' => 'Aftercare Products',
                'description' => 'Complete aftercare package bundle',
                'cost_price' => 750.00,
                'selling_price' => 750.00,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'unit' => 'set',
                'supplier' => 'K-Derma Supplies',
                'expiry_date' => now()->addMonths(24),
                'is_active' => true,
            ],

            // Aesthetic Creams (for laser treatments)
            [
                'name' => 'Aesthetic Cream',
                'sku' => 'AEC-001',
                'category' => 'Laser Treatment Products',
                'description' => 'Specialized cream for laser treatments',
                'cost_price' => 0.00,
                'selling_price' => null,
                'current_stock' => 25,
                'minimum_stock' => 5,
                'unit' => 'tube',
                'supplier' => 'Medical Supplies Co.',
                'expiry_date' => now()->addMonths(12),
                'is_active' => true,
            ],
            [
                'name' => 'AE Cream',
                'sku' => 'AE-001',
                'category' => 'Laser Treatment Products',
                'description' => 'Advanced aesthetic cream for laser procedures',
                'cost_price' => 0.00,
                'selling_price' => null,
                'current_stock' => 25,
                'minimum_stock' => 5,
                'unit' => 'tube',
                'supplier' => 'Medical Supplies Co.',
                'expiry_date' => now()->addMonths(12),
                'is_active' => true,
            ],
            [
                'name' => 'Hydrocort',
                'sku' => 'HC-001',
                'category' => 'Laser Treatment Products',
                'description' => 'Hydrocortisone cream for post-laser care',
                'cost_price' => 0.00,
                'selling_price' => null,
                'current_stock' => 30,
                'minimum_stock' => 8,
                'unit' => 'tube',
                'supplier' => 'Medical Supplies Co.',
                'expiry_date' => now()->addMonths(18),
                'is_active' => true,
            ],

            // Equipment Treatment Products
            [
                'name' => 'Gel Cream',
                'sku' => 'GC-001',
                'category' => 'Equipment Treatment Products',
                'description' => 'Conductive gel cream for equipment-based treatments',
                'cost_price' => 0.00,
                'selling_price' => null,
                'current_stock' => 40,
                'minimum_stock' => 10,
                'unit' => 'tube',
                'supplier' => 'Equipment Supplies Ltd.',
                'expiry_date' => now()->addMonths(18),
                'is_active' => true,
            ],

            // Gluta Products
            [
                'name' => 'Gluta Product',
                'sku' => 'GP-001',
                'category' => 'Whitening Products',
                'description' => 'Glutathione-based whitening product (serum)',
                'cost_price' => 0.00,
                'selling_price' => null,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'unit' => 'vial',
                'supplier' => 'Beauty Solutions Inc.',
                'expiry_date' => now()->addMonths(12),
                'is_active' => true,
            ],

            // Treatment Products for Facial
            [
                'name' => 'Aloe Vera',
                'sku' => 'AV-001',
                'category' => 'Facial Treatment Products',
                'description' => 'Pure aloe vera gel for facial treatments',
                'cost_price' => 0.00,
                'selling_price' => null,
                'current_stock' => 35,
                'minimum_stock' => 10,
                'unit' => 'bottle',
                'supplier' => 'Natural Products Co.',
                'expiry_date' => now()->addMonths(12),
                'is_active' => true,
            ],
            [
                'name' => 'Foaming Wash (Treatment)',
                'sku' => 'FWT-001',
                'category' => 'Facial Treatment Products',
                'description' => 'Professional foaming wash for facial treatments',
                'cost_price' => 0.00,
                'selling_price' => null,
                'current_stock' => 30,
                'minimum_stock' => 8,
                'unit' => 'bottle',
                'supplier' => 'Professional Skincare Ltd.',
                'expiry_date' => now()->addMonths(18),
                'is_active' => true,
            ],
            [
                'name' => 'Facial Scrub',
                'sku' => 'FS-001',
                'category' => 'Facial Treatment Products',
                'description' => 'Exfoliating scrub for facial treatments',
                'cost_price' => 0.00,
                'selling_price' => null,
                'current_stock' => 25,
                'minimum_stock' => 5,
                'unit' => 'jar',
                'supplier' => 'Professional Skincare Ltd.',
                'expiry_date' => now()->addMonths(15),
                'is_active' => true,
            ],
            [
                'name' => 'Carbon Gel',
                'sku' => 'CG-001',
                'category' => 'Facial Treatment Products',
                'description' => 'Carbon-based gel for specialized facial treatments',
                'cost_price' => 0.00,
                'selling_price' => null,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'unit' => 'tube',
                'supplier' => 'Advanced Skincare Solutions',
                'expiry_date' => now()->addMonths(12),
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            InventoryItem::create($product);
        }
    }
}
